name: Simple GitHub Actions Workflow

on: 
  push:
    branches:
      - main  # Triggers workflow on a push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3  # Checks out the repository code

      - name: Run a Basic Command
        run: echo "Hello, GitHub Actions!"  # Prints message in logs

